name: my_project
repository: https://github.com/khiari-youssef/SesaLife_Flutter

packages:
  - application
  - features/**
  - infrastructure/**
  - test-runner/**


scripts:
  analyze:
    exec: dart analyze .