name: notifications_feature
description: "This package contains all screens and components related to notifications feature"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  designsystem:
    path: ../../infrastructure/designsystem
  shared_dependencies:
    path: ../../infrastructure/shared_dependencies
  core:
    path: ../../infrastructure/core

dev_dependencies:
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_gen: ^5.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0


flutter:
   generate: true
