name: users_management_feature
description: "All usecases related to user actions, user data..."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  designsystem:
    path: ../../infrastructure/designsystem
  shared_dependencies:
    path: ../../infrastructure/shared_dependencies
  core:
    path: ../../infrastructure/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_gen: ^5.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
