name: core
description: "This package bundles all the core domain and data utilities and services to be used across project features"
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  shared_dependencies:
    path: ../shared_dependencies
  designsystem:
    path: ../designsystem
  qr_code_scanner: ^1.0.1
  local_auth: ^2.2.0
  qrscan: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  flutter_gen: ^5.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true