name: SesameLife CI build workflow
run-name: ${{ github.actor }} is running build workflow
on:
  push:
    branches:
      - main
jobs:
  releaseBuild:
    runs-on: macos-14
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: | # optional
           sub-project/*.gradle*
           sub-project/**/gradle-wrapper.properties
      - run: ./gradlew build --no-daemon
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Check flutter environment requirements
        run: flutter doctor --verbose
        with:
          channel: stable
          flutter-version: 3.22.1
      - run: flutter --version
      - run: sh build.sh
      - run: cd test-runner && test test/testAppRunner_test.dart
      - run: sh release.sh
      - run: echo "job completed successfully ! "


