name: SesameLife CI build workflow
run-name: ${{ github.actor }} is running build workflow
on:
  push:
    branches:
      - main
jobs:
  installFlutter:
    runs-on: macOS
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1
      - run: flutter --version
      - run: job completed successfully !


